const ROLES = require('./roles');
const PERMISSIONS = require('./permissions');

const ROLE_PERMISSIONS = {
  [ROLES.BUYER]: [
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.ORDER_READ,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.SELLER_APPLICATION_CREATE,
    PERMISSIONS.SELLER_APPLICATION_READ_OWN,
    PERMISSIONS.SELLER_APPLICATION_UPDATE_OWN,
    PERMISSIONS.SELLER_APPLICATION_SUBMIT,
    PERMISSIONS.SELLER_APPLICATION_CANCEL,
  ],

  [ROLES.SELLER]: [
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_UPDATE,
    PERMISSIONS.PRODUCT_DELETE,
    PERMISSIONS.ORDER_READ,
    PERMISSIONS.ORDER_UPDATE,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.SELLER_APPLICATION_READ_OWN,
    PERMISSIONS.STORE_READ_OWN,
    PERMISSIONS.STORE_UPDATE_OWN,
  ],

  [ROLES.ADMIN]: Object.values(PERMISSIONS),
};

module.exports = ROLE_PERMISSIONS;